kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-role-binding
  namespace: "default"
subjects:
- kind: ServiceAccount
  name: k8s-sa
roleRef:
  kind: Role
  name: sa-role
  apiGroup: rbac.authorization.k8s.io